name: 'No Worries '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d2a5a93f-47b3-49dc-92a2-3344750f39bc.jpg
layout_spectrum: 0.61402
typography_spectrum: 0.206925
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#A0A088'
    - '#484020'
    - '#908868'
    - '#B19D4E'
    - '#000000'
  brandStrength: 0.684121
  lightness: 0.521114
  saturation: 0.498806
  rhythmicContrast: 0.499155
purpose: []
title: Future Businesses site
author:
  name: Mindy Davis
  url: ''
  email: beepresent.ms@gmail.com
content_rating:
  adult: false
