name: Honest Contracting WITH HEART
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d2a5a93f-47b3-49dc-92a2-3344750f39bc.jpg
layout_spectrum: 0.2456103137228638
typography_spectrum: 0.4638454045634717
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.1916473989840597
  lightness: 0.26280256430618465
  saturation: 0.3750178636983037
  rhythmicContrast: 0.5974150297697634
purpose: []
title: Future Businesses site
author:
  name: Mindy Davis
  url: ''
  email: beepresent.ms@gmail.com
content_rating:
  adult: false
coverPrefs:
  filter: false
