analytics: {}
color:
  brandColors:
    - '#A0A088'
    - '#484020'
    - '#908868'
    - '#B19D4E'
    - '#000000'
  brandStrength: 0.684121
  lightness: 0.521114
  rhythmicContrast: 0.499155
  saturation: 0.498806
cta: {}
layout_spectrum: 0.44184572622179985
name: 'No Worries '
opengraph: {}
purpose: []
typography_spectrum: 0.4090154250152409
